In [4]:
import pandas as pd
import geopandas as gpd

In [1]:

geo_frame = gpd.read_file("LEHD_data/U.S._Census_Blocks/Census_Blocks.shp")

data = pd.read_csv("LEHD_data/oh_rac_S000_JT00_2004_2013.csv")

data['h_geocode'] = data['h_geocode'].astype(str)
geo_frame.head()
geo_frame['STATE'] = geo_frame['STATE'].astype(str).str.zfill(2)  # State code is 2 digits
geo_frame['COUNTY'] = geo_frame['COUNTY'].astype(str).str.zfill(3)  # County codes are 3 digits
geo_frame['TRACT'] = geo_frame['TRACT'].astype(str).str.zfill(6)  # Tract codes are 6 digits
geo_frame['BLOCK'] = geo_frame['BLOCK'].astype(str).str.zfill(4)  # Block codes are 4 digits
geo_frame['h_geocode'] = (geo_frame['STATE']) + (geo_frame['COUNTY']) + (geo_frame['TRACT'])+ (geo_frame['BLOCK'])

mergedFrame = pd.merge(data, geo_frame, on = 'h_geocode', how='inner')
mergedFrame.head()

,h_geocode,C000,CA01,CA02,CA03,CE01,CE02,CE03,CNS01,CNS02,...,ObjID,STATE,SUFFIX,TRACT,UR,HU100,POP100,SHAPE_Leng,SHAPE_Area,geometry
0,390351011011000,67,24,40,3,20,40,7,0,0,...,210701004127841,39,None,101101,None,69.0,170.0,0.009466,0.000004,"POLYGON ((-81.74427 41.48166, -81.74425 41.481..."
1,390351011011001,89,29,53,7,29,46,14,0,0,...,210701004127840,39,None,101101,None,84.0,170.0,0.009503,0.000003,"POLYGON ((-81.74514 41.48419, -81.74451 41.484..."
2,390351011011003,74,20,47,7,18,40,16,0,1,...,210701004132117,39,None,101101,None,107.0,196.0,0.008447,0.000004,"POLYGON ((-81.74859 41.48290, -81.74848 41.482..."
3,390351011011004,68,21,43,4,26,39,3,0,0,...,210701004127824,39,None,101101,None,70.0,154.0,0.008815,0.000004,"POLYGON ((-81.74733 41.48338, -81.74627 41.483..."
4,390351011011005,101,26,63,12,32,60,9,0,1,...,210701004132121,39,None,101101,None,93.0,228.0,0.009530,0.000004,"POLYGON ((-81.74627 41.48377, -81.74514 41.484..."

In [3]:
data = pd.read_csv("LEHD_data/CuyahogaCountyRAC_SHP.csv")

year = data.groupby('h_geocode')
year.head()
year.describe()

                 C000                                                       \
                count   mean         std   min    25%   50%     75%    max
h_geocode
390351011011000  10.0  190.7  166.350400  58.0  66.25  76.5  365.25  432.0
390351011011001  10.0   65.3   17.416786  44.0  51.75  63.0   71.75   98.0
390351011011002   1.0    3.0         NaN   3.0   3.00   3.0    3.00    3.0
390351011011003  10.0   58.1   14.325191  36.0  51.25  55.0   71.00   79.0
390351011011004  10.0   58.7   14.173920  39.0  47.25  58.5   67.00   83.0
...               ...    ...         ...   ...    ...   ...     ...    ...
390359811001018   3.0    3.0    0.000000   3.0   3.00   3.0    3.00    3.0
390359900000001  10.0   13.1    4.863698   6.0  10.00  12.5   16.00   21.0
390359900000002  10.0   13.9    5.506562   6.0   9.50  12.5   18.00   22.0
390359900000003  10.0   26.9   10.115445  13.0  16.75  30.5   35.75   38.0
390359900000004  10.0   12.3    4.715224   6.0   9.25  11.5   14.50   22.0

                 CA01             ... SHAPE_Leng           SHAPE_Area  \
                count       mean  ...        75%       max      count
h_geocode                         ...
390351011011000  10.0  60.100000  ...   0.009466  0.009466       10.0
390351011011001  10.0  18.200000  ...   0.009503  0.009503       10.0
390351011011002   1.0   1.000000  ...   0.008880  0.008880        1.0
390351011011003  10.0  14.700000  ...   0.008447  0.008447       10.0
390351011011004  10.0  17.500000  ...   0.008815  0.008815       10.0
...               ...        ...  ...        ...       ...        ...
390359811001018   3.0   0.666667  ...   0.001547  0.001547        3.0
390359900000001  10.0   3.700000  ...   1.062924  1.062924       10.0
390359900000002  10.0   4.100000  ...   1.211401  1.211401       10.0
390359900000003  10.0   7.300000  ...   1.201816  1.201816       10.0
390359900000004  10.0   3.100000  ...   1.219924  1.219924       10.0

                                                                         \
                         mean           std           min           25%
h_geocode
390351011011000  3.765431e-06  4.464256e-22  3.765431e-06  3.765431e-06
390351011011001  3.479304e-06  0.000000e+00  3.479304e-06  3.479304e-06
390351011011002  9.592872e-07           NaN  9.592872e-07  9.592872e-07
390351011011003  3.634452e-06  4.464256e-22  3.634452e-06  3.634452e-06
390351011011004  3.564826e-06  4.464256e-22  3.564826e-06  3.564826e-06
...                       ...           ...           ...           ...
390359811001018  1.338499e-07  0.000000e+00  1.338499e-07  1.338499e-07
390359900000001  2.828265e-02  0.000000e+00  2.828265e-02  2.828265e-02
390359900000002  5.355653e-02  0.000000e+00  5.355653e-02  5.355653e-02
390359900000003  5.829510e-02  0.000000e+00  5.829510e-02  5.829510e-02
390359900000004  7.754860e-02  0.000000e+00  7.754860e-02  7.754860e-02


                          50%           75%           max
h_geocode
390351011011000  3.765431e-06  3.765431e-06  3.765431e-06
390351011011001  3.479304e-06  3.479304e-06  3.479304e-06
390351011011002  9.592872e-07  9.592872e-07  9.592872e-07
390351011011003  3.634452e-06  3.634452e-06  3.634452e-06
390351011011004  3.564826e-06  3.564826e-06  3.564826e-06
...                       ...           ...           ...
390359811001018  1.338499e-07  1.338499e-07  1.338499e-07
390359900000001  2.828265e-02  2.828265e-02  2.828265e-02
390359900000002  5.355653e-02  5.355653e-02  5.355653e-02
390359900000003  5.829510e-02  5.829510e-02  5.829510e-02
390359900000004  7.754860e-02  7.754860e-02  7.754860e-02

[13560 rows x 512 columns]

In [2]:
healthLine = gpd.read_file("LEHD_data/HealthLine.shp")
healthLine.head()

,name,geometry
0,Cleveland RTA HealthLine BRT,"LINESTRING (-9094214.631 5086299.333, -9094075..."

In [11]:
access = pd.read_csv("LEHD_data/HealthLineAccess.csv")
access.head()
access['STATE'] = access['STATE'].astype(str).str.zfill(2)  # State code is 2 digits
access['COUNTY'] = access['COUNTY'].astype(str).str.zfill(3)  # County codes are 3 digits
access['TRACT'] = access['TRACT'].astype(str).str.zfill(6)  # Tract codes are 6 digits
access['BLOCK'] = access['BLOCK'].astype(str).str.zfill(4)  # Block codes are 4 digits
access['h_geocode'] = (access['STATE']) + (access['COUNTY']) + (access['TRACT'])+ (access['BLOCK'])
access.head()
access['HealthLine'] = access['pctTransitAccess'] > 0.25
access['HealthLine'] = access['HealthLine'].astype(int)
access.head()

,OBJECTID,BLKGRP,BLOCK,COUNTY,STATE,TRACT,BlockArea,Name,description,timestamp,...,altitudeMode,tessellate,extrude,visibility,drawOrder,icon,bufferArea,pctTransitAccess,h_geocode,HealthLine
0,1503362,2,2005,035,39,198500,47481.242285,Cleveland RTA HealthLine BRT,NaN,NaN,...,NaN,-1,0,-1,NaN,NaN,29865.954661,0.629005,390351985002005,1
1,1503363,3,3007,035,39,107101,8588.914771,Cleveland RTA HealthLine BRT,NaN,NaN,...,NaN,-1,0,-1,NaN,NaN,8588.914771,1.000000,390351071013007,1
2,1503545,3,3016,035,39,116800,5683.285614,Cleveland RTA HealthLine BRT,NaN,NaN,...,NaN,-1,0,-1,NaN,NaN,620.608633,0.109199,390351168003016,0
3,1503548,2,2008,035,39,150300,19741.678795,Cleveland RTA HealthLine BRT,NaN,NaN,...,NaN,-1,0,-1,NaN,NaN,14858.838974,0.752663,390351503002008,1
4,1503549,2,2007,035,39,150300,23318.705295,Cleveland RTA HealthLine BRT,NaN,NaN,...,NaN,-1,0,-1,NaN,NaN,23318.705295,1.000000,390351503002007,1

In [33]:
data = pd.read_csv("LEHD_data/CuyahogaCountyRAC_SHP.csv")
print(data.columns)
data.head()
data['year'].value_counts()
data['h_geocode'] = data['h_geocode'].astype(str)
merged = pd.merge(data, access, on = 'h_geocode', how = 'left')
merged.head()
merged['HealthLine'] = merged['HealthLine'].fillna(0)
merged['After'] = merged['year'] > 2008
merged['After'] = merged['After'].astype(int)
merged['HealthLine'].value_counts()
merged['After'].value_counts()
merged['healthline_x_after'] = merged['HealthLine'] * merged['After']
merged['healthline_x_after'].value_counts()

datadictionary = {
    'C000': 'total_jobs',
    'CA01': 'total_29_and_under',
    'CA02': 'total_30_54',
    'CA03': 'total_55_and_over',
    'CE01': 'total_under_1250per_month',
    'CE02': 'total_1250_3333per_month',
    'CE03': 'total_3334_and_up_per_month',
    'CNS01': 'agriculture_forestry_fishing_hunting',
    'CNS02': 'mining_quarrying_oil_gas_extraction',
    'CNS03': 'utilities',
    'CNS04': 'construction',
    'CNS05': 'manufacturing',
    'CNS06': 'wholesale_trade',
    'CNS07': 'retail_trade',
    'CNS08': 'transportation_warehousing',
    'CNS09': 'information',
    'CNS10': 'finance_insurance',
    'CNS11': 'real_estate_rental_leasing',
    'CNS12': 'professional_scientific_technical_services',
    'CNS13': 'management_of_companies_enterprises',
    'CNS14': 'admin_support_waste_mgmt_remediation_services',
    'CNS15': 'educational_services',
    'CNS16': 'health_care_social_assistance',
    'CNS17': 'arts_entertainment_recreation',
    'CNS18': 'accommodation_food_services',
    'CNS19': 'other_services_except_public_administration',
    'CNS20': 'public_administration',
    'CR01': 'race_white',
    'CR02': 'race_black',
    'CR03': 'race_american_indian_alaska_native',
    'CR04': 'race_asian',
    'CR05': 'race_native_hawaiian_other_pacific_islander',
    'CR07': 'race_two_or_more',
    'CT01': 'ethnicity_not_hispanic_latino',
    'CT02': 'ethnicity_hispanic_latino',
    'CD01': 'less_than_HS',
    'CD02': 'HS_GED',
    'CD03': 'Some_college_or_associates_degree',
    'CD04': 'Bachelors_or_higher',
    'CS01': 'sex_male',
    'CS02': 'sex_female'
}

for key, value in datadictionary.items():
    merged.rename(columns={key: value}, inplace=True)

print(merged.columns)

merged.to_csv("LEHD_data/FinalJobData.csv", index=False)

Index(['h_geocode', 'C000', 'CA01', 'CA02', 'CA03', 'CE01', 'CE02', 'CE03',
       'CNS01', 'CNS02', 'CNS03', 'CNS04', 'CNS05', 'CNS06', 'CNS07', 'CNS08',
       'CNS09', 'CNS10', 'CNS11', 'CNS12', 'CNS13', 'CNS14', 'CNS15', 'CNS16',
       'CNS17', 'CNS18', 'CNS19', 'CNS20', 'CR01', 'CR02', 'CR03', 'CR04',
       'CR05', 'CR07', 'CT01', 'CT02', 'CD01', 'CD02', 'CD03', 'CD04', 'CS01',
       'CS02', 'createdate', 'year', 'OBJECTID', 'AREALAND', 'AREAWATER',
       'BASENAME', 'BLKGRP', 'BLOCK', 'CENTLAT', 'CENTLON', 'COUNTY',
       'FUNCSTAT', 'GEOID', 'INTPTLAT', 'INTPTLON', 'LSADC', 'LWBLKTYP',
       'MTFCC', 'NAME', 'ObjID', 'STATE', 'SUFFIX', 'TRACT', 'UR', 'HU100',
       'POP100', 'SHAPE_Leng', 'SHAPE_Area', 'geometry'],
      dtype='object')
Index(['h_geocode', 'total_jobs', 'total_29_and_under', 'total_30_54',
       'total_55_and_over', 'total_under_1250per_month',
       'total_1250_3333per_month', 'total_3334_and_up_per_month',
       'agriculture_forestry_fishing_hunting',
       'mining_quarrying_oil_gas_extraction', 'utilities', 'construction',
       'manufacturing', 'wholesale_trade', 'retail_trade',
       'transportation_warehousing', 'information', 'finance_insurance',
       'real_estate_rental_leasing',
       'professional_scientific_technical_services',
       'management_of_companies_enterprises',
       'admin_support_waste_mgmt_remediation_services', 'educational_services',
       'health_care_social_assistance', 'arts_entertainment_recreation',
       'accommodation_food_services',
       'other_services_except_public_administration', 'public_administration',
       'race_white', 'race_black', 'race_american_indian_alaska_native',
       'race_asian', 'race_native_hawaiian_other_pacific_islander',
       'race_two_or_more', 'ethnicity_not_hispanic_latino',
       'ethnicity_hispanic_latino', 'less_than_HS', 'HS_GED',
       'Some_college_or_associates_degree', 'Bachelors_or_higher', 'sex_male',
       'sex_female', 'createdate', 'year', 'OBJECTID_x', 'AREALAND',
       'AREAWATER', 'BASENAME', 'BLKGRP_x', 'BLOCK_x', 'CENTLAT', 'CENTLON',
       'COUNTY_x', 'FUNCSTAT', 'GEOID', 'INTPTLAT', 'INTPTLON', 'LSADC',
       'LWBLKTYP', 'MTFCC', 'NAME', 'ObjID', 'STATE_x', 'SUFFIX', 'TRACT_x',
       'UR', 'HU100', 'POP100', 'SHAPE_Leng', 'SHAPE_Area', 'geometry',
       'OBJECTID_y', 'BLKGRP_y', 'BLOCK_y', 'COUNTY_y', 'STATE_y', 'TRACT_y',
       'BlockArea', 'Name', 'description', 'timestamp', 'begin', 'end',
       'altitudeMode', 'tessellate', 'extrude', 'visibility', 'drawOrder',
       'icon', 'bufferArea', 'pctTransitAccess', 'HealthLine', 'After',
       'healthline_x_after'],
      dtype='object')

In [37]:
import matplotlib.pyplot as plt
summary_stats = merged.groupby(['year', 'HealthLine']).describe()
print(summary_stats)

summary_stats.to_csv("LEHD_data/SummaryStats.csv")

                total_jobs                                                \
                     count       mean        std  min   25%   50%    75%
year HealthLine
2004 0.0           12461.0  48.231603  55.062898  1.0  17.0  35.0  59.00
     1.0             497.0  33.275654  50.050604  1.0   7.0  21.0  43.00
2005 0.0           12433.0  48.066517  54.786452  1.0  17.0  35.0  59.00
     1.0             483.0  32.819876  53.929517  1.0   7.0  20.0  42.00
2006 0.0           12456.0  47.081166  54.377320  1.0  16.0  35.0  58.00
     1.0             499.0  31.513026  51.420361  1.0   6.0  19.0  39.00
2007 0.0           12455.0  47.084384  54.559168  1.0  16.0  34.0  58.00
     1.0             487.0  31.498973  54.623699  1.0   6.0  19.0  39.00
2008 0.0           12396.0  45.646741  61.184491  1.0  14.0  29.0  51.00
     1.0             478.0  31.525105  54.974726  1.0   6.0  17.0  35.00
2009 0.0           12382.0  41.444920  48.582559  1.0  14.0  30.0  51.00
     1.0             484.0  27.301653  43.891405  1.0   6.0  16.0  33.00
2010 0.0           12418.0  42.461749  52.135177  1.0  14.0  30.0  51.00
     1.0             487.0  27.209446  43.423521  1.0   5.5  16.0  33.00
2011 0.0           12218.0  44.267065  70.609148  1.0  13.0  27.0  48.00
     1.0             468.0  28.764957  50.071087  1.0   6.0  14.5  31.25
2012 0.0           12206.0  44.563084  70.772876  1.0  13.0  27.0  48.00
     1.0             472.0  28.563559  50.346951  1.0   5.0  14.0  32.00
2013 0.0           12227.0  44.958453  71.612379  1.0  13.0  27.0  48.00
     1.0             458.0  30.203057  53.131028  1.0   6.0  15.0  32.00

                        total_29_and_under             ... After       \
                    max              count       mean  ...   75%  max
year HealthLine                                        ...
2004 0.0          791.0            12461.0  11.439531  ...   0.0  0.0
     1.0          657.0              497.0   9.818913  ...   0.0  0.0
2005 0.0          808.0            12433.0  11.422102  ...   0.0  0.0
     1.0          722.0              483.0  10.080745  ...   0.0  0.0
2006 0.0          815.0            12456.0  11.069123  ...   0.0  0.0
     1.0          723.0              499.0   9.635271  ...   0.0  0.0
2007 0.0          787.0            12455.0  11.006503  ...   0.0  0.0
     1.0          800.0              487.0   9.967146  ...   0.0  0.0
2008 0.0         1043.0            12396.0  10.851323  ...   0.0  0.0
     1.0          787.0              478.0  10.087866  ...   0.0  0.0
2009 0.0          790.0            12382.0   9.616459  ...   1.0  1.0
     1.0          603.0              484.0   8.477273  ...   1.0  1.0
2010 0.0          719.0            12418.0   9.539378  ...   1.0  1.0
     1.0          616.0              487.0   8.129363  ...   1.0  1.0
2011 0.0         1424.0            12218.0   9.978884  ...   1.0  1.0
     1.0          490.0              468.0   8.923077  ...   1.0  1.0
2012 0.0         1361.0            12206.0   9.871293  ...   1.0  1.0
     1.0          500.0              472.0   8.769068  ...   1.0  1.0
2013 0.0         1332.0            12227.0  10.140182  ...   1.0  1.0
     1.0          504.0              458.0   9.641921  ...   1.0  1.0

                healthline_x_after
                             count mean  std  min  25%  50%  75%  max
year HealthLine
2004 0.0                   12461.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     497.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2005 0.0                   12433.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     483.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2006 0.0                   12456.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     499.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2007 0.0                   12455.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     487.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2008 0.0                   12396.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     478.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2009 0.0                   12382.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     484.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
2010 0.0                   12418.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     487.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
2011 0.0                   12218.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     468.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
2012 0.0                   12206.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     472.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
2013 0.0                   12227.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
     1.0                     458.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

[20 rows x 640 columns]

In [44]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
merged.groupby(['year', 'HealthLine'])
HealthLine = merged[merged['HealthLine'] == 1]
nonHealthLine = merged[merged['HealthLine'] == 0]
HealthLine = HealthLine.groupby('year').mean()
nonHealthLine = nonHealthLine.groupby('year').mean()


# Plot the data
plt.figure(figsize=(10, 6))
plt.plot(HealthLine['year'], HealthLine['total_jobs'], label='HealthLine/Euclid Corridor', color = 'black', linestyle='solid')
plt.plot(nonHealthLine['year'], nonHealthLine['total_jobs'], label='Rest of Cleveland', color = 'black', linestyle='dashed')
plt.xlabel('Year')
plt.ylabel('Total Jobs')
plt.title('Number of Jobs per Census Block for residents in HealthLine Corridor vs. Rest of Cuyahoga County')

# Set x-axis to show only the year
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.gca().xaxis.set_major_locator(mdates.YearLocator())

# Add a vertical line for a specific date
plt.axvline(pd.to_datetime('2009'), color='gray', linestyle='dotted', linewidth=1)
plt.xlim(2004,2013)

plt.legend()
plt.show()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
# Plot the data
plt.figure(figsize=(10, 6))
plt.plot(HealthLine['year'], HealthLine['total_jobs'], label='HealthLine/Euclid Corridor', color = 'black', linestyle='solid')
plt.plot(nonHealthLine['year'], nonHealthLine['total_jobs'], label='Rest of Cleveland', color = 'black', linestyle='dashed')
plt.xlabel('Year')
plt.ylabel('Total Jobs')
plt.title('Number of Jobs for residents in HealthLine Corridor vs. Rest of Cleveland')

# Set x-axis to show only the year
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.gca().xaxis.set_major_locator(mdates.YearLocator())

# Add a vertical line for a specific date
plt.axvline(pd.to_datetime('2009'), color='gray', linestyle='dotted', linewidth=1)

# Set x-axis limits
plt.xlim([pd.to_datetime('2018-09-01'), pd.to_datetime('2020-01-01')])

plt.legend()
plt.show()

In [ ]:
# Plot the data
plt.figure(figsize=(10, 6))
plt.plot(HealthLine['year'], HealthLine['total_jobs'], label='HealthLine/Euclid Corridor', color = 'black', linestyle='solid')
plt.plot(nonHealthLine['year'], nonHealthLine['total_jobs'], label='Rest of Cleveland', color = 'black', linestyle='dashed')
plt.xlabel('Year')
plt.ylabel('Total Jobs')
plt.title('Number of Jobs for residents in HealthLine Corridor vs. Rest of Cleveland')

# Set x-axis to show only the year
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.gca().xaxis.set_major_locator(mdates.YearLocator())

# Add a vertical line for a specific date
plt.axvline(pd.to_datetime('2009'), color='gray', linestyle='dotted', linewidth=1)

# Set x-axis limits
plt.xlim([pd.to_datetime('2018-09-01'), pd.to_datetime('2020-01-01')])

plt.legend()
plt.show()